- hosts: [terraform-ansible]
  tasks:
  - name: criando arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Toto</h1>
  - name: criando servidor
    shell: "nohup busybox httpd -f -p 8080 &"
